version: '3'
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
    angular:
        container_name : angular
        build: ./front/angularclient
        restart: always
        ports:
        - 4200:4200
    mysql:
        container_name: mysql
        image: mysql/mysql-server:latest
        environment:
            MYSQL_DATABASE: projet fullstack
            MYSQL_ROOT_PASSWORD: Formation123
            MYSQL_ROOT_HOST: '%'
        ports:
        - "3306:3306"
        restart: always
    springboot:
        restart : always
        build:
            context: ./back/fullstackproject
            dockerfile: Dockerfile
        working_dir: /springboot
        volumes:
        - ./springboot:/springboot
        - ~/.m2:/root/.m2
        expose:
        - "8080"
        depends_on:
        - nginx
        - mysql
        command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker